from .animal import Animal
from .pet import Pet
from .beast_of_burden import BeastOfBurden
from .Camel import Camel
from .Cat import Cat
from .Dog import Dog
from .Donkey import Donkey
from .Hamster import Hamster
from .Horse import Horse
from .counter import Counter
from .AnimalRegistry import AnimalRegistry